const projects = [
  {
    id: 1,
    live_link: "https://bright-pixie-d9a05d.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/bd-reminder",
    title: "birthday reminder",
    image: "/images/bd.png",
  },
  {
    id: 2,
    live_link: "https://cheery-sunburst-dd12cc.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/navbar",
    title: "navbar",
    image: "/images/navbar.png",
  },
  {
    id: 3,
    live_link: "https://willowy-toffee-b3e575.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/stripe",
    title: "stripe",
    image: "/images/stripe.png",
  },
  {
    id: 4,
    live_link: "https://fascinating-snickerdoodle-197277.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/cocktails",
    title: "cocktails",
    image: "/images/cocktails.png",
  },
  {
    id: 5,
    live_link: "https://roaring-salmiakki-c8c91d.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/cart",
    title: "cart",
    image: "/images/cart.png",
  },
  {
    id: 6,
    live_link: "https://stupendous-puppy-efb6db.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/sidebar",
    title: "sidebar",
    image: "/images/sidebar.png",
  },
  {
    id: 7,
    live_link: "https://glistening-sfogliatella-50da2a.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/tabs",
    title: "tabs",
    image: "/images/bd.png",
  },
  {
    id: 8,
    live_link: "https://brilliant-fox-501a47.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/slider",
    title: "slider",
    image: "/images/slider.png",
  },
  {
    id: 9,
    live_link: "https://soft-bublanina-693e5b.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/lourem-ipsum",
    title: "lourem ipsum",
    image: "/images/lourem.png",
  },
  {
    id: 10,
    live_link: "https://magnificent-empanada-a34de9.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/menu",
    title: "menu",
    image: "/images/menu.png",
  },
  {
    id: 11,
    live_link: "https://taupe-sundae-e423d5.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/views",
    title: "views",
    image: "/images/views.png",
  },
  {
    id: 12,
    live_link: "https://fantastic-begonia-53aac7.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/tours",
    title: "tours",
    image: "/images/tours.png",
  },
  {
    id: 13,
    live_link: "https://sweet-moxie-8a620c.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/accordian",
    title: "accordian",
    image: "/images/bd.png",
  },
  {
    id: 14,
    live_link:
      "https://62fb805e78f0171810ea92ef--capable-biscochitos-7dc2a3.netlify.app/",
    github_link: "https://github.com/MUJTABA1998/blog-we",
    title: "Blog Site",
    image: "/images/bd.png",
  },
];

export default projects;
